#!/bin/bash

CURRENT_SOURCE=$(pactl info | grep "Default Source" | cut -f3 -d" ")

if [[ $(pactl list sources | grep -A 10 $CURRENT_SOURCE | grep "yes") == *"Mute"* ]] # Weird error with colons
then
  echo 1 | sudo tee /sys/class/leds/platform\:\:micmute/brightness
else
  echo 0 | sudo tee /sys/class/leds/platform\:\:micmute/brightness
fi
