#!/usr/bin/sh

sxhkd &
autorandr --change

# bspc monitor -d I II III IV V VI VII VIII IX X

PRIMARY_MONITOR=$(xrandr | awk '/ primary / {print $1}')

ALL_MONITORS=$(xrandr |awk '/ connected/{print $1}')

#bspc monitor $PRIMARY_MONITOR -d 1 2 3

# Mobile
if [[ $PRIMARY_MONITOR = "eDP-1" ]]
then
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi

# Full
if [[ $PRIMARY_MONITOR = "HDMI-1-0" ]] && [[ $ALL_MONITORS == *"DP-1-0"* ]]
then
  bspc monitor HDMI-1-0 -d 1 2 3 4
  bspc monitor DP-1-0 -d 5 6 7 8 9
fi

# Center Only
if [[ $PRIMARY_MONITOR = "HDMI-1-0" ]] && [[ $ALL_MONITORS != *"DP-1-0"* ]]
then
  bspc monitor HDMI-1-0 -d 1 2 3 4
  bspc monitor eDP-1 -d 5 6 7 8 9
fi

# Left Only
if [[ $PRIMARY_MONITOR = "DP-1-0" ]] && [[ $ALL_MONITORS != *"HDMI-1-0"* ]]
then
  bspc monitor DP-1-0 -d 1 2 3 4
  bspc monitor eDP-1 -d	5 6 7 8 9
fi

bspc monitor DP-1-0 4 5 6
#bspc monitor HDMI-1-0

bspc config border_width         5
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/Pictures/Wallpapers/1.jpg
