#!/usr/bin/sh

notify-send "bspwm" "Reloading bspwmrc"

sxhkd &
autorandr --change
# ~/.config/polybar/launch.sh
xfce4-power-manager &
# Required for VMWare Workstation
/usr/libexec/polkit-gnome-authentication-agent-1 &
ibus-daemon -drxR

export XDG_CURRENT_DESKTOP="bspwm"
PRIMARY_MONITOR=$(xrandr | awk '/ primary / {print $1}')
ALL_MONITORS=$(xrandr |awk '/ connected/{print $1}')

# Mobile
#bspc monitor eDP-1 -r
#bspc monitor HDMI-1-0 -r
#bspc monitor DP-1-0 -r
# bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
if [[ $PRIMARY_MONITOR = "eDP-1" ]]
then
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
  # Move Monitors
  bspc monitor HDMI-1-0 -a Desktop > /dev/null
  for desktop in $(seq 1 9)
  do
         echo "Moving desktop $desktop to moitor eDP-1"
	 bspc desktop $desktop --to-monitor eDP-1
  done
  bspc monitor eDP-1 -o 1 2 3 4 5 6 7 8 9
  bspc monitor --remove HDMI-1-0 > /dev/null
  bspc desktop Desktop -r
  notify-send "Monitor" "Mobile Mode"
elif [[ $PRIMARY_MONITOR = "HDMI-1-0" ]] && [[ $ALL_MONITORS == *"DP-1-0"* ]] && [[ $ALL_MONITORS == *"eDP-1"* ]] #All
then
  bspc monitor HDMI-1-0 -d 1 2 3
  bspc monitor DP-1-0 -d 4 5 6
  bspc monitor eDP-1 -d 7 8 9
  notify-send "Monitor" "Full Mode"
elif [[ $PRIMARY_MONITOR = "HDMI-1-0" ]] && [[ $ALL_MONITORS != *"DP-1-0"* ]]
then
#  bspc monitor HDMI-1-0 -d 1 2 3 4
#  bspc monitor eDP-1 -d 5 6 7 8 9
  notify-send "Monitor" "Centre Only Mode"
  for i in `seq 1 5`
  do
    echo "Move Desktop $i to monitor HDMI-1-0"
    bspc desktop $i --to-monitor HDMI-1-0
  done

  for i in `seq 6 9`
  do
    echo "Move Desktop $i to monitor eDP-1"
    bspc desktop $i --to-monitor eDP-1
  done

  # bspc monitor HDMI-1-0 -d 1 2 3 4 5
  # bspc monitor eDP-1 -d 6 7 8 9
  # bspc wm -r 
  bspc monitor HDMI-1-0 -o 1 2 3 4 5
  bspc monitor eDP-1 -o 6 7 8 9
  bspc desktop Desktop -r
elif [[ $PRIMARY_MONITOR = "DP-1-0" ]] && [[ $ALL_MONITORS != *"HDMI-1-0"* ]]
then
  bspc monitor DP-1-0 -d 1 2 3 4
  bspc monitor eDP-1 -d	5 6 7 8 9
  notify-send "Monitor" "Left Only Mode"
fi

bspc config border_width         4
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 40

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a scratchpad sticky=on state=floating hidden=on
# check scratchpad already running
#[ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && st -c scratchpad -e ~/bin/scratch &

# feh --bg-fill /home/wren/mnt/Data/personal/wallpapers/2023Q1/owl.jpg
feh --bg-max /home/wren/Documents/Wallpapers/104510108_p0.jpg
# ~/.config/polybar/launch.sh
